# Generated by Django 4.1.2 on 2022-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='images/None/Noimg.jpg', upload_to='images/'),
        ),
    ]
